name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - name: x86-unicode
            unicode: ON
            arch: Win32
            triplet: x86-windows-static
          - name: x86-ansi
            unicode: OFF
            arch: Win32
            triplet: x86-windows-static
          - name: x64-unicode
            unicode: ON
            arch: x64
            triplet: x64-windows-static
          - name: x64-ansi
            unicode: OFF
            arch: x64
            triplet: x64-windows-static

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure
        run: cmake -S . -B build ^
          -DUNICODE=${{ matrix.unicode }} ^
          -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} ^
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake ^
          -DCMAKE_BUILD_TYPE=Release ^
          -A ${{ matrix.arch }}

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: build/${{ matrix.name }}

  package:
    runs-on: windows-latest
    needs: [build, test]
    steps:
      - name: Download all builds
        uses: actions/download-artifact@v4
        with:
          path: Plugin

      - name: Create ZIP
        run: powershell Compress-Archive -Path Plugin -DestinationPath nscj-plugin.zip

      - name: Upload final artifact
        uses: actions/upload-artifact@v4
        with:
          name: nscj-plugin
          path: nscj-plugin.zip

      # -----------------------------
      # Create GitHub Release automatically
      # -----------------------------
      # - name: Create GitHub Release
      #   if: startsWith(github.ref, 'refs/tags/')
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ github.ref_name }}
      #     name: Release ${{ github.ref_name }}
      #     body: "Automatic release generated by GitHub Actions"
      #     draft: false
      #     prerelease: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload release asset
      #   if: startsWith(github.ref, 'refs/tags/')
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: nscj-plugin.zip
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
